apiVersion: landscape.config.gardener.cloud/v1alpha1
kind: LandscapeKitConfiguration
# ocm:
#   repositories:
#   - <repo-url>
#   rootComponent:
#     name: <component-name>
#     version: <component-version>
#   originalRefs: true
repositories:
  base:
    componentsFiles:
    - components.yaml
  landscape:
    ref:
      # branch: main
      tag: main
    baseLink: ./base
    kind: OCIRepository
    url: oci://glk-registry.local.gardener.cloud:6001/landscape
    # url: http://gitops:testtest@git.local.gardener.cloud:6080/gitops/test-landscape.git
components:
  include:
  - flux
  - github
