name: Push OCI

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: docker
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      id-token: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.9.3

      - name: Push artefact to registry
        run: |
          STAGE="$HOME/artifact"
          mkdir -p "$STAGE"
          cp -a "$GITHUB_WORKSPACE/." "$STAGE/"
          flux push artifact \
            oci://glk-registry.local.gardener.cloud:6001/landscape:${{ github.ref_name }} \
            --insecure-registry \
            --path="$STAGE" \
            --source="$(git config --get remote.origin.url)" \
            --revision="${{ github.ref_name }}@sha1:${{ github.sha }}"
